import { FormPath } from '@uform/core';
import { IFormActions, IAsyncFormActions } from '@uform/types';
import { registerFieldMiddleware, registerFormFieldPropsTransformer, registerFormField, registerFormFields, registerFormWrapper } from './shared/core';
import { calculateSchemaInitialValues } from './utils';
export * from './type';
export * from './shared/virtualbox';
export * from './decorators/connect';
export * from './shared/broadcast';
export * from './shared/array';
export declare const SchemaForm: any;
export declare const Field: (props: any) => any;
export declare const setValidationLocale: (locale: import("@uform/validator").ILocales) => void;
export declare const setValidationLanguage: (lang: string) => void;
export declare const createFormActions: () => IFormActions;
export declare const createAsyncFormActions: () => IAsyncFormActions;
export { registerFormField, registerFormFields, registerFormWrapper, registerFieldMiddleware, registerFormFieldPropsTransformer, calculateSchemaInitialValues, FormPath };
export default SchemaForm;
